#!/usr/bin/env bash
# vendor/INTEGRITY.sha256 üretir: vendor/ altındaki her dosyanın (AUDIT-ALLOW ve REVIEW.md dahil) sha256'sı.
# Kullanım: bash scripts/gen-integrity.sh        (gen-manifest.sh bunu da çağırır)
# Platformlar arası birebir çıktı için: LC_ALL=C sıralama; Git Bash'in '*' (ikili) ayracı Linux'un çift boşluğuna normalize edilir.
set -eu
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; cd "$ROOT"
{ echo "# sha256 of every tracked file under vendor/ — generated by scripts/gen-integrity.sh; verify with scripts/verify-integrity.sh"
  find vendor -type f ! -name INTEGRITY.sha256 ! -name .audit-status -print0 \
    | LC_ALL=C sort -z | xargs -0 sha256sum | sed -E 's/\r$//; s/^([0-9a-f]{64}) [ *]/\1  /'; } > vendor/INTEGRITY.sha256
echo "$(($(wc -l < vendor/INTEGRITY.sha256)-1)) dosya → vendor/INTEGRITY.sha256"
